### ISSUE TITLE
Recompile for KSP 1.4.x

### ISSUE THREAD

**Issue by Gordon-Dry** [Kopernicus/Kronometer#11]
Let's begin with adding issues.

**Comment by Sigma88** [comment]
are you saying it doesn't work?

kronometer is not version locked, which means it should work fine unless some changes broke it.

if you have an issue to report, here's a guide on what files we need to debug this issue

[how to ask for support](http://forum.kerbalspaceprogram.com/index.php?/topic/140580-0/&page=27#comment-2793409)

**Comment by Gordon-Dry** [comment]
I tried it a few weeks ago, it didn't work.

As I found a post in "some" forum thread that it's not working, I felt confirmed.

And when I understand it correctly; Kronometer is built not only upon KSP but also upon Kopernicus, and that one changed, too.

**Comment by Sigma88** [comment]
no, kronometer is independent from kopernicus, you should be able to run it without kopernicus

**Comment by Sigma88** [comment]
even tho you still haven't provided any of the files I required I decided to spend some of my limited free time to test if kronometer is actually failing on KSP 1.4.3

turns out it works perfectly fine

![image](https://user-images.githubusercontent.com/12640834/40670917-bc995c0e-636a-11e8-8f32-d467c2297a4e.png)

this means that your issue is probably caused by incompatibility with another mod rather than KSP itself.

**Comment by Gordon-Dry** [comment]
Okay, then these 2 circumstances had misguided me.

**Comment by Sigma88** [comment]
btw, I tested it both with and without kopernicus (latest version)

kronometer worked in both cases

**Comment by Galileo88** [comment]
🙄
